version: "3.2"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/pinfo/backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=hello_world.settings.development
    stdin_open: true
    tty: true
    command: python3 manage.py runserver 0.0.0.0:8000
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/pinfo
      # One-way volume to use node_modules from inside image
      - /pinfo/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start
